name: "Odoo Release"
description: "Create a new release from the manifest"
runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - id: compare-versions
      name: Compare current version with latest release
      run: python3 ${{ github.action_path }}/compare_versions.py
      shell: bash

    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v1
      if: ${{ steps.compare-versions.outputs.new-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.compare-versions.outputs.new-version }}
        tag_name: ${{ steps.compare-versions.outputs.new-version }}
        draft: false
        prerelease: false
